### PR TITLE
US-87 full integration 

### PR DESCRIPTION
**Pull request by djitmett**
- Requires formal code review
- This is the complete US-87 ready for full integration merge

### CODE REVIEW

**Comment by jrhall14** [comment]
Author: Darya, Corey and Josh
Reviewer: Josh
US 87
-Defect type : none
-Confirmation : Time log feature implemented and no bugs discovered.
-Coding standards : Approved

**Comment by djitmett** [comment]
Author: Corey, Darya, & Josh
Reviewer: Darya
US 87
-Defect type : None / Enhancement

-Confirmation : Confirmation that the time log panel is working without error. 
No defects discovered.

-Coding standards : Coding standards are met & proper removal of dead code was implemented.

Approval for merge.

**Comment by crakes** [comment]
Author: Darya, Josh, Corey
Reviewer: Corey
US 87
-Defect type : none
-Confirmation: Timelog panel works with no errors. All tasks perform as advertised.
-Coding standards : mege
Approve for merge

**Comment by jadixon5** [comment]
Author: Darya, Corey and Josh
Reviewer: Jason
US 87
-Defect type : none
-Confirmation : Time log feature implemented and no bugs discovered.
-Coding standards : Approved

**Pull request merged**
