### PR TITLE
US 70 full integration

### PR DESCRIPTION
**Pull request by djitmett**

### CODE REVIEW

**Comment by djitmett** [comment]
Author: Tong
Reviewer: Darya
US 70

-Defect type : None

-Confirmation : Confirmation that the timer works and updates actual effort.
- Confirmation energy levels are displayed and counter as you re-open the program
*note* need to add jars to build path in order to work

-Coding standards : Coding standards are met.

Approval for merge.

**Comment by crakes** [comment]
Author: Tong
Reviewer: Corey
US 70
-Defect type : None / Enhancement

-Confirmation : Confirmation that the stop watch works and updates Act Effort. The graph shows the number of instances of memoranda used.

-Coding standards : Coding standards are met & proper removal of dead code was implemented.

Approval for merge.

**Comment by jrhall14** [comment]
Author: Tong
Reviewer: Josh (as part of Formal Review)
US 70 
-Defect type : none
-Confirmation : Added energy graph and stopwatch updates actual effort.
-Coding standards : Approved

**Comment by jadixon5** [comment]
Author: Tong
Reviewer: Jason
US 70
-Defect type : none
-Confirmation : Added energy graph and stopwatch updates actual effort.
-Coding standards : Approved

**Pull request merged**
