### PR TITLE
US 119 full integration

### PR DESCRIPTION
**Pull request by djitmett**
Formal code review required

### CODE REVIEW

**Comment by jrhall14** [comment]
Author: Darya
Reviewer: Josh
US 118
-Defect type : Enhancement
-Confirmation : Added look and feel options work as expected.
-Coding standards : Approved

**Comment by djitmett** [comment]
Author: Darya
Reviewer: Darya
US 118
-Defect type : Enhancement
-Confirmation : Look and feel options work with no conflict; export sticker is in english.
-Coding standards : Coding standards met.

Approved for merge.

**Comment by jadixon5** [comment]
Author: Darya
Reviewer: Jason
US 118
-Defect type : Enhancement
-Confirmation : Added look and feel options work as expected.
-Coding standards : Approved

**Comment by crakes** [comment]
Author: Darya
Reviewer: Corey
US 118
-Defect type : Enhancement
-Confirmation : Added the ability to change the look and feel of the GUI. 
-Coding standards : Approved

**Comment by crakes** [comment]
Author: All
Reviewer: Corey
Before release
-Defect type : All task
-Confirmation : Integration and regression test check good
-Coding standards : Approved

**Pull request merged**
